module two_factor_auth_controller #(
    parameter MAX_PWD_RETRIES  = 3,
    parameter MAX_OTP_RETRIES  = 3,
    parameter OTP_TIMEOUT_LIMIT = 10
)(
    input clk,
    input reset,

    input       password_submit,
    input       password_valid,
    input       otp_submit,
    input       otp_valid,
    input       timeout_tick,

    output reg       access_granted,
    output reg       locked_out,
    output reg       request_otp,
    output reg [1:0] pwd_fail_count,
    output reg [1:0] otp_fail_count,
    output reg [3:0] otp_timeout_counter
);

    // =========================================================
    // STATE DEFINITIONS
    // =========================================================
    localparam PASSWORD_ENTRY    = 3'b000;
    localparam PASSWORD_VERIFIED = 3'b001;
    localparam OTP_SENT          = 3'b010;
    localparam OTP_VERIFY        = 3'b011;
    localparam ACCESS_GRANTED    = 3'b100;
    localparam LOCKED            = 3'b101;

    reg [2:0] state;
    reg [2:0] next_state;

    // =========================================================
    // STATE REGISTER AND COUNTERS
    // =========================================================
    always @(posedge clk) begin
        if (reset) begin
            state               <= PASSWORD_ENTRY;
            pwd_fail_count      <= 2'd0;
            otp_fail_count      <= 2'd0;
            otp_timeout_counter <= 4'd0;
        end
        else begin
            state <= next_state;

            case (state)

                // -------------------------------------------------
                // PASSWORD ENTRY
                // -------------------------------------------------
                PASSWORD_ENTRY: begin
                    if (password_submit) begin

                        if (password_valid) begin
                            pwd_fail_count <= 2'd0;
                        end
                        else begin
                            // SECURITY:
                            // Increment on every failed password attempt.
                            // The next-state logic locks on the 3rd failure.
                            if (pwd_fail_count < MAX_PWD_RETRIES)
                                pwd_fail_count <= pwd_fail_count + 1'b1;
                        end
                    end
                end

                // -------------------------------------------------
                // PASSWORD VERIFIED
                // -------------------------------------------------
                PASSWORD_VERIFIED: begin
                    // Start a fresh OTP timeout window.
                    otp_timeout_counter <= 4'd0;
                end

                // -------------------------------------------------
                // OTP SENT
                // -------------------------------------------------
                OTP_SENT: begin
                    // OTP request is generated by the output logic
                    // for this one-cycle state.
                    otp_timeout_counter <= 4'd0;
                end

                // -------------------------------------------------
                // OTP VERIFY
                // -------------------------------------------------
                OTP_VERIFY: begin

                    if (otp_submit) begin
                        // OTP submission takes priority over timeout.
                        otp_timeout_counter <= 4'd0;

                        if (otp_valid) begin
                            otp_fail_count <= 2'd0;
                        end
                        else begin
                            // SECURITY:
                            // Increment OTP failure count for a wrong OTP.
                            if (otp_fail_count < MAX_OTP_RETRIES)
                                otp_fail_count <= otp_fail_count + 1'b1;
                        end
                    end
                    else if (timeout_tick) begin

                        // SECURITY:
                        // Count timeout_tick pulses. When the current
                        // count reaches LIMIT-1, this tick is the final
                        // timeout interval and counts as one failed OTP.
                        if (otp_timeout_counter < OTP_TIMEOUT_LIMIT) begin
                            if (otp_timeout_counter + 1 >= OTP_TIMEOUT_LIMIT) begin
                                otp_timeout_counter <= 4'd0;

                                if (otp_fail_count < MAX_OTP_RETRIES)
                                    otp_fail_count <= otp_fail_count + 1'b1;
                            end
                            else begin
                                otp_timeout_counter <=
                                    otp_timeout_counter + 1'b1;
                            end
                        end
                    end
                end

                // -------------------------------------------------
                // ACCESS GRANTED
                // -------------------------------------------------
                ACCESS_GRANTED: begin
                    // Authentication completed successfully.
                    // Hold all values until reset.
                    state <= ACCESS_GRANTED;
                end

                // -------------------------------------------------
                // LOCKED
                // -------------------------------------------------
                LOCKED: begin
                    // SECURITY:
                    // LOCKED is a permanent state until synchronous
                    // reset. No normal operation can exit this state.
                    state <= LOCKED;
                end

                default: begin
                    state               <= PASSWORD_ENTRY;
                    pwd_fail_count      <= 2'd0;
                    otp_fail_count      <= 2'd0;
                    otp_timeout_counter <= 4'd0;
                end

            endcase
        end
    end

    // =========================================================
    // NEXT-STATE COMBINATIONAL LOGIC
    // =========================================================
    always @(*) begin
        next_state = state;

        case (state)

            // -------------------------------------------------
            // PASSWORD ENTRY
            // -------------------------------------------------
            PASSWORD_ENTRY: begin
                if (password_submit) begin

                    if (password_valid) begin
                        next_state = PASSWORD_VERIFIED;
                    end
                    else if ((pwd_fail_count + 1) >= MAX_PWD_RETRIES) begin
                        // SECURITY:
                        // Third failed password attempt forces LOCKED.
                        next_state = LOCKED;
                    end
                    else begin
                        next_state = PASSWORD_ENTRY;
                    end
                end
            end

            // -------------------------------------------------
            // PASSWORD VERIFIED
            // -------------------------------------------------
            PASSWORD_VERIFIED: begin
                next_state = OTP_SENT;
            end

            // -------------------------------------------------
            // OTP SENT
            // -------------------------------------------------
            OTP_SENT: begin
                // This is a one-cycle OTP request state.
                next_state = OTP_VERIFY;
            end

            // -------------------------------------------------
            // OTP VERIFY
            // -------------------------------------------------
            OTP_VERIFY: begin

                if (otp_submit) begin

                    if (otp_valid) begin
                        next_state = ACCESS_GRANTED;
                    end
                    else if ((otp_fail_count + 1) >= MAX_OTP_RETRIES) begin
                        // SECURITY:
                        // Third failed OTP attempt forces LOCKED.
                        next_state = LOCKED;
                    end
                    else begin
                        // Wrong OTP -> request a new OTP.
                        next_state = OTP_SENT;
                    end
                end
                else if (timeout_tick &&
                         ((otp_timeout_counter + 1) >= OTP_TIMEOUT_LIMIT)) begin

                    // SECURITY:
                    // Expired OTP timeout counts as one failed OTP attempt.
                    // A third timeout/failure forces permanent LOCKED.
                    if ((otp_fail_count + 1) >= MAX_OTP_RETRIES)
                        next_state = LOCKED;
                    else
                        next_state = OTP_SENT;
                end
                else begin
                    next_state = OTP_VERIFY;
                end
            end

            // -------------------------------------------------
            // ACCESS GRANTED
            // -------------------------------------------------
            ACCESS_GRANTED: begin
                next_state = ACCESS_GRANTED;
            end

            // -------------------------------------------------
            // LOCKED
            // -------------------------------------------------
            LOCKED: begin
                // SECURITY:
                // No transition out of LOCKED is allowed.
                // Only the reset branch in the sequential block
                // can return the FSM to PASSWORD_ENTRY.
                next_state = LOCKED;
            end

            default: begin
                next_state = PASSWORD_ENTRY;
            end

        endcase
    end

    // =========================================================
    // OUTPUT LOGIC
    // =========================================================
    always @(*) begin

        access_granted = 1'b0;
        locked_out     = 1'b0;

        // OTP_SENT lasts exactly one clock cycle, so request_otp
        // is a one-cycle pulse for every new OTP request.
        request_otp = (state == OTP_SENT);

        case (state)

            PASSWORD_ENTRY: begin
                access_granted = 1'b0;
                locked_out     = 1'b0;
            end

            PASSWORD_VERIFIED: begin
                access_granted = 1'b0;
                locked_out     = 1'b0;
            end

            OTP_SENT: begin
                access_granted = 1'b0;
                locked_out     = 1'b0;
            end

            OTP_VERIFY: begin
                access_granted = 1'b0;
                locked_out     = 1'b0;
            end

            ACCESS_GRANTED: begin
                access_granted = 1'b1;
                locked_out     = 1'b0;
            end

            LOCKED: begin
                // SECURITY:
                // Access is unconditionally denied while LOCKED.
                access_granted = 1'b0;
                locked_out     = 1'b1;
            end

            default: begin
                access_granted = 1'b0;
                locked_out     = 1'b0;
            end

        endcase
    end

endmodule
